services:
  - type: web
    name: blog
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
